// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHJoIihboBlYoYaJrEVfDITmujwhvmNkw',
    appId: '1:900702129256:web:d2fd669aa2092e062dbfdd',
    messagingSenderId: '900702129256',
    projectId: 'flutterconnection-173c2',
    authDomain: 'flutterconnection-173c2.firebaseapp.com',
    storageBucket: 'flutterconnection-173c2.appspot.com',
    measurementId: 'G-QS77L060S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBkb8BmVmVUy7XOX03k9iIgr-zUTqYlH0',
    appId: '1:900702129256:android:04d72786002752d12dbfdd',
    messagingSenderId: '900702129256',
    projectId: 'flutterconnection-173c2',
    storageBucket: 'flutterconnection-173c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMXBuDArmVtWOZNjROLMqFisiMjV8Fa4k',
    appId: '1:900702129256:ios:52d02677c53c5edb2dbfdd',
    messagingSenderId: '900702129256',
    projectId: 'flutterconnection-173c2',
    storageBucket: 'flutterconnection-173c2.appspot.com',
    iosBundleId: 'com.example.flutterConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMXBuDArmVtWOZNjROLMqFisiMjV8Fa4k',
    appId: '1:900702129256:ios:52d02677c53c5edb2dbfdd',
    messagingSenderId: '900702129256',
    projectId: 'flutterconnection-173c2',
    storageBucket: 'flutterconnection-173c2.appspot.com',
    iosBundleId: 'com.example.flutterConnection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHJoIihboBlYoYaJrEVfDITmujwhvmNkw',
    appId: '1:900702129256:web:36266786d2d457af2dbfdd',
    messagingSenderId: '900702129256',
    projectId: 'flutterconnection-173c2',
    authDomain: 'flutterconnection-173c2.firebaseapp.com',
    storageBucket: 'flutterconnection-173c2.appspot.com',
    measurementId: 'G-L2QMVYF238',
  );
}
